# See https://pre-commit.com for more information

# Setting ruff linting & formatting.
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.4
  hooks:
    # Run the linter.
    - id: ruff
      args: ['--extend-select=I', --fix ]
    # Run the formatter.
    - id: ruff-format