# Use a base image with Python installed
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the contents of the src/agent directory to the working directory
COPY / /app/src/agent

# Install dependencies using uv
RUN pip install uv && \
    uv pip install -r src/agent/requirements.txt --system

# Set the default command to run the application
CMD ["uvicorn", "src.agent.server:app", "--host", "0.0.0.0", "--port", "8501"]

