# Use a base image with Python installed
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the contents of the src/agent directory to the working directory
COPY / /app/src/chatbot

# Install dependencies using uv
RUN pip install uv && \
    uv pip install -r src/chatbot/requirements.txt --system

# Set the default command to run the application
ENTRYPOINT ["uvicorn", "src.chatbot.server:app"]

