services:
# AI-ChatBot-Server
  chatbot-server:
    build:
      context: ../src/agent/
      dockerfile: dockerfile
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      MODEL_REPO_ID: ${MODEL_REPO_ID}
      DATABASE_URL: "postgres:5432"
    ports:
      - 8501:8501
    depends_on:
      - postgres

# Postgres Database
  postgres:
    image: postgres:17.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"
    
    # Make sure `volume` stays on ext4 FS to avoid issues
    volumes:
      # - ./init-scripts:/docker-entrypoint-initdb.d  # Mount initialization scripts
      - /home/darklord/Downloads/db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

networks:
  default:
    name: ChatBot-Network
    driver: bridge
